export const ADD = 'ADD';

export const REMOVE = 'REMOVE';

export const LOG_IN = 'LOG_IN';
export const FETCH_MY_LIST = 'FETCH_MY_LIST';
export const FETCH_RECOMMEND_LIST = 'FETCH_RECOMMEND_LIST';
export const SELECT_SINGLE_SELECTION = 'SELECT_SINGLE_SELECTION';
export const SELECT_MULTIPLE_SELECTION = 'SELECT_MULTIPLE_SELECTION';
export const SELECT_SINGLE_MUSIC = 'SELECT_SINGLE_MUSIC';
export const SELECT_MULTIPLE_MUSIC = 'SELECT_MULTIPLE_MUSIC';
export const DELETE_SELECT_MUSIC = 'DELETE_SELECT_MUSIC';
export const RENAME_SELECT_MUSIC = 'RENAME_SELECT_MUSIC';
export const CHANGE_MUSIC_BMPANDEMP = 'CHANGE_MUSIC_BMPANDEMP';
export const CLEAR_MUSIC_BMPANDEMP = 'CLEAR_MUSIC_BMPANDEMP';
